services:
  - name: docker:20.10-dind
    command: ["--tls=false"]

variables:
  APP_IMAGE_NAME: yermanov/news-platform
  APP_IMAGE_TAG: dev
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .gradle/
    - build/

run_tests:
  stage: test
  image: bellsoft/liberica-openjdk-debian:17
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew clean test

build_docker_image:
  stage: build
  image: docker:20.10.16
  before_script:
    - apk update && apk add openjdk17
    - chmod +x ./gradlew
    - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN
  script:
    - ./gradlew clean bootBuildImage -PimageName=$APP_IMAGE_NAME -PimageTag=$APP_IMAGE_TAG
    - docker push $APP_IMAGE_NAME:$APP_IMAGE_TAG
