version: '3.5'
services:
  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672-5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.14.2
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms256m"
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
      xpack.security.enabled: "true"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  logstash:
    image: logstash:7.14.2
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms256m"
      ELASTIC_USER: elastic
      ELASTIC_PASSWORD: elastic
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: elastic
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: elastic
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "host.docker.internal:9200"
      XPACK_MONITORING_ENABLED: "true"
    volumes:
      - "./pipeline:/usr/share/logstash/pipeline"
    restart: unless-stopped
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.14.2
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - logstash


volumes:
  elasticsearch:
