version: '3.5'
services:
  postgres:
    container_name: postgres-container
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    image: elasticsearch:7.14.2
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms256m"
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
      xpack.security.enabled: "true"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  logstash:
    image: logstash:7.14.2
    ports:
      - "5001:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms256m"
      ELASTIC_USER: elastic
      ELASTIC_PASSWORD: elastic
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: elastic
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: elastic
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "host.docker.internal:9200"
      XPACK_MONITORING_ENABLED: "true"
    volumes:
      - "./pipeline:/usr/share/logstash/pipeline"
    restart: unless-stopped
    depends_on:
      - elasticsearch

  minio:
    container_name: minio-container
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9090:9090"
      - "9000:9000"
    restart: always
    command: server -console-address :9090 /data
  kibana:
    image: kibana:7.14.2
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - logstash

volumes:
  elasticsearch:
  postgres-data:
  minio-data:
