spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: /
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update



yandex:
  key: AQVNx2ftCoiiO9jQPe-NYuJGrxnqMURC2kXayxY4

logging:
  level:
    com.example.yt: DEBUG


minio:
  bucket-name: news
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

springdoc:
  swagger-ui:
    operations-sorter: method
  override-with-generic-response: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token-expiration: 86400000 # a day
      refresh-token-expiration: 604800000 # 7 days

  time-zone: Z